# Generated by Django 4.1.7 on 2023-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude')),
                ('lon', models.CharField(max_length=20, verbose_name='Longitude')),
                ('inverterPower', models.CharField(max_length=5, verbose_name='Inverter power')),
                ('gridConnectedTime', models.DateTimeField(verbose_name='Grid connected time')),
                ('abs_val', models.CharField(max_length=10, verbose_name='Current power')),
                ('use', models.CharField(max_length=10, verbose_name='Daily energy')),
                ('pv', models.CharField(max_length=10, verbose_name='Year energy')),
                ('name', models.DateTimeField(auto_now_add=True, verbose_name='Name search')),
            ],
        ),
        migrations.CreateModel(
            name='Huawei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=15, verbose_name='User name')),
                ('p_word', models.CharField(max_length=15, verbose_name='Password')),
                ('sub_domain', models.CharField(max_length=10, verbose_name='Subdomain')),
            ],
        ),
    ]
