# Generated by Django 4.1.7 on 2023-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0002_data_regions_alter_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name search'),
        ),
        migrations.AlterField(
            model_name='data',
            name='regions',
            field=models.CharField(max_length=20, verbose_name='Regions'),
        ),
    ]
