# Generated by Django 4.1.7 on 2023-08-03 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0003_alter_data_name_alter_data_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='adress',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Adress'),
            preserve_default=False,
        ),
    ]
