# Generated by Django 4.1.7 on 2023-08-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0004_data_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=35, verbose_name='User name')),
                ('sn', models.CharField(max_length=35, verbose_name='User name')),
                ('lat', models.CharField(max_length=35, verbose_name='User name')),
                ('lon', models.CharField(max_length=35, verbose_name='User name')),
                ('name', models.CharField(max_length=35, verbose_name='User name')),
            ],
        ),
    ]
