# Generated by Django 4.1.7 on 2023-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0005_solax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solax',
            name='lat',
            field=models.CharField(max_length=35, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='solax',
            name='lon',
            field=models.CharField(max_length=35, verbose_name='Lon'),
        ),
        migrations.AlterField(
            model_name='solax',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Stantion name'),
        ),
        migrations.AlterField(
            model_name='solax',
            name='sn',
            field=models.CharField(max_length=35, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='solax',
            name='token',
            field=models.CharField(max_length=35, verbose_name='Token'),
        ),
    ]
