# Generated by Django 4.1.7 on 2023-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0006_alter_solax_lat_alter_solax_lon_alter_solax_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solax',
            name='inverterPower',
            field=models.CharField(default='None', max_length=35, verbose_name='inverterPower'),
        ),
    ]
