# Generated by Django 4.1.7 on 2023-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0007_solax_inverterpower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solax',
            name='inverterPower',
            field=models.CharField(default='30 kW', max_length=35, verbose_name='inverterPower'),
        ),
    ]
