# Generated by Django 4.1.7 on 2023-09-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0008_alter_solax_inverterpower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=15, verbose_name='User name')),
                ('a_word', models.CharField(max_length=15, verbose_name='Password')),
            ],
        ),
    ]
