# Generated by Django 4.2.5 on 2023-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0009_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteo_id', models.CharField(max_length=35, verbose_name='ID')),
                ('lat', models.CharField(max_length=35, verbose_name='Lat')),
                ('lon', models.CharField(max_length=35, verbose_name='Lon')),
                ('name', models.CharField(max_length=35, verbose_name='Stantion name')),
            ],
        ),
    ]
