# Generated by Django 4.2.5 on 2023-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0010_meteodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('shortwave_radiation_instant', models.CharField(max_length=35, verbose_name='Shortwave radiation instant')),
                ('temperature_2m', models.CharField(max_length=35, verbose_name='Temperature 2m')),
                ('windspeed_10m', models.CharField(max_length=35, verbose_name='Windspeed 10m')),
                ('relativehumidity_2m', models.CharField(default='None', max_length=35, verbose_name='Relativehumidity 2m')),
            ],
        ),
    ]
