# Generated by Django 4.2.5 on 2023-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0011_openmeteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Real',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('meteo_id', models.CharField(max_length=35, verbose_name='Meteo Id')),
                ('temp', models.CharField(max_length=35, verbose_name='Temperature')),
                ('t_air_min', models.CharField(max_length=35, verbose_name='Min temperature')),
                ('t_air_max', models.CharField(default='None', max_length=35, verbose_name='Max temperature')),
                ('rel_hum', models.CharField(default='None', max_length=35, verbose_name='Relativehumidity 2m')),
                ('windspeed', models.CharField(default='None', max_length=35, verbose_name='Windspeed 10m')),
                ('winddir', models.CharField(default='None', max_length=35, verbose_name='winddir')),
                ('solarradiation', models.CharField(default='None', max_length=35, verbose_name='Shortwave radiation instant')),
            ],
        ),
    ]
