# Generated by Django 4.2.5 on 2023-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0013_real_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Real_2',
        ),
        migrations.AlterField(
            model_name='real',
            name='solarradiation',
            field=models.CharField(default='0', max_length=35, verbose_name='Shortwave radiation instant'),
        ),
    ]
