# Generated by Django 4.2.5 on 2023-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0014_delete_real_2_alter_real_solarradiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='abs_val',
            field=models.FloatField(max_length=10, verbose_name='Current power'),
        ),
        migrations.AlterField(
            model_name='data',
            name='inverterPower',
            field=models.FloatField(max_length=5, verbose_name='Inverter power'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pv',
            field=models.FloatField(max_length=10, verbose_name='Year energy'),
        ),
        migrations.AlterField(
            model_name='data',
            name='use',
            field=models.FloatField(max_length=10, verbose_name='Daily energy'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='lat',
            field=models.FloatField(max_length=35, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='lon',
            field=models.FloatField(max_length=35, verbose_name='Lon'),
        ),
        migrations.AlterField(
            model_name='openmeteo',
            name='relativehumidity_2m',
            field=models.FloatField(default='None', max_length=35, verbose_name='Relativehumidity 2m'),
        ),
        migrations.AlterField(
            model_name='openmeteo',
            name='shortwave_radiation_instant',
            field=models.FloatField(max_length=35, verbose_name='Shortwave radiation instant'),
        ),
        migrations.AlterField(
            model_name='openmeteo',
            name='temperature_2m',
            field=models.FloatField(max_length=35, verbose_name='Temperature 2m'),
        ),
        migrations.AlterField(
            model_name='openmeteo',
            name='windspeed_10m',
            field=models.FloatField(max_length=35, verbose_name='Windspeed 10m'),
        ),
        migrations.AlterField(
            model_name='real',
            name='meteo_id',
            field=models.FloatField(max_length=35, verbose_name='Meteo Id'),
        ),
        migrations.AlterField(
            model_name='real',
            name='rel_hum',
            field=models.FloatField(default='None', max_length=35, verbose_name='Relativehumidity 2m'),
        ),
        migrations.AlterField(
            model_name='real',
            name='solarradiation',
            field=models.FloatField(default='0', max_length=35, verbose_name='Shortwave radiation instant'),
        ),
        migrations.AlterField(
            model_name='real',
            name='t_air_max',
            field=models.FloatField(default='None', max_length=35, verbose_name='Max temperature'),
        ),
        migrations.AlterField(
            model_name='real',
            name='t_air_min',
            field=models.FloatField(max_length=35, verbose_name='Min temperature'),
        ),
        migrations.AlterField(
            model_name='real',
            name='temp',
            field=models.FloatField(max_length=35, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='real',
            name='winddir',
            field=models.FloatField(default='None', max_length=35, verbose_name='winddir'),
        ),
        migrations.AlterField(
            model_name='real',
            name='windspeed',
            field=models.FloatField(default='None', max_length=35, verbose_name='Windspeed 10m'),
        ),
        migrations.AlterField(
            model_name='solax',
            name='inverterPower',
            field=models.FloatField(default='30 kW', max_length=35, verbose_name='inverterPower'),
        ),
        migrations.AlterField(
            model_name='solax',
            name='lat',
            field=models.FloatField(max_length=35, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='solax',
            name='lon',
            field=models.FloatField(max_length=35, verbose_name='Lon'),
        ),
    ]
