# Generated by Django 4.2.5 on 2023-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0015_alter_data_abs_val_alter_data_inverterpower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real',
            name='meteo_id',
            field=models.FloatField(default='None', max_length=35, verbose_name='Meteo Id'),
        ),
        migrations.AlterField(
            model_name='real',
            name='t_air_min',
            field=models.FloatField(default='None', max_length=35, verbose_name='Min temperature'),
        ),
        migrations.AlterField(
            model_name='real',
            name='temp',
            field=models.FloatField(default='None', max_length=35, verbose_name='Temperature'),
        ),
    ]
