# Generated by Django 4.2.5 on 2023-11-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0016_alter_real_meteo_id_alter_real_t_air_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real',
            name='meteo_id',
            field=models.FloatField(default=0, max_length=35, verbose_name='Meteo Id'),
        ),
        migrations.AlterField(
            model_name='real',
            name='rel_hum',
            field=models.FloatField(default=0, max_length=35, verbose_name='Relativehumidity 2m'),
        ),
        migrations.AlterField(
            model_name='real',
            name='solarradiation',
            field=models.FloatField(default=0, max_length=35, verbose_name='Shortwave radiation instant'),
        ),
        migrations.AlterField(
            model_name='real',
            name='t_air_max',
            field=models.FloatField(default=0, max_length=35, verbose_name='Max temperature'),
        ),
        migrations.AlterField(
            model_name='real',
            name='t_air_min',
            field=models.FloatField(default=0, max_length=35, verbose_name='Min temperature'),
        ),
        migrations.AlterField(
            model_name='real',
            name='temp',
            field=models.FloatField(default=0, max_length=35, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='real',
            name='winddir',
            field=models.FloatField(default=0, max_length=35, verbose_name='winddir'),
        ),
        migrations.AlterField(
            model_name='real',
            name='windspeed',
            field=models.FloatField(default=0, max_length=35, verbose_name='Windspeed 10m'),
        ),
    ]
