# Generated by Django 4.2.5 on 2023-11-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0017_alter_real_meteo_id_alter_real_rel_hum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Real_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('meteo_id', models.FloatField(default=0, max_length=35, verbose_name='Meteo Id')),
                ('temp', models.FloatField(default=0, max_length=35, verbose_name='Temperature')),
                ('t_air_min', models.FloatField(default=0, max_length=35, verbose_name='Min temperature')),
                ('t_air_max', models.FloatField(default=0, max_length=35, verbose_name='Max temperature')),
                ('rel_hum', models.FloatField(default=0, max_length=35, verbose_name='Relativehumidity 2m')),
                ('windspeed', models.FloatField(default=0, max_length=35, verbose_name='Windspeed 10m')),
                ('winddir', models.FloatField(default=0, max_length=35, verbose_name='winddir')),
            ],
        ),
    ]
