# Generated by Django 4.2.5 on 2023-11-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0018_real_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Real_2',
        ),
    ]
