# Generated by Django 4.2.5 on 2023-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0019_delete_real_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real',
            name='solarradiation',
            field=models.FloatField(blank=True, default=0.0, max_length=35, null=True, verbose_name='Shortwave radiation instant'),
        ),
    ]
