# Generated by Django 4.2.5 on 2023-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0020_alter_real_solarradiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real',
            name='meteo_id',
            field=models.CharField(max_length=35, verbose_name='Meteo Id'),
        ),
    ]
