# Generated by Django 4.2.5 on 2023-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0021_alter_real_meteo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('get_id', models.CharField(max_length=35, verbose_name='Meteo Id')),
                ('real_power', models.FloatField(default=0, max_length=35, verbose_name='Relativehumidity 2m')),
                ('abs_power', models.FloatField(default=0, max_length=35, verbose_name='Windspeed 10m')),
            ],
        ),
    ]
