# Generated by Django 4.2.5 on 2023-12-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0022_getdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdata',
            name='total_power',
            field=models.FloatField(default=0, max_length=35, verbose_name='Windspeed 10m'),
        ),
    ]
