# Generated by Django 4.2.5 on 2023-12-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0023_getdata_total_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getdata',
            old_name='total_power',
            new_name='year_power',
        ),
    ]
