# Generated by Django 4.2.5 on 2023-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapproject', '0024_rename_total_power_getdata_year_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='get_id',
            field=models.CharField(default='None', max_length=35, verbose_name='Meteo Id'),
        ),
    ]
